/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assg;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class M_BookAppointments extends javax.swing.JFrame {

    private DefaultTableModel table;
    private String username;
    private String[][] waitingAppointmentList;
    /**
     * Creates new form M_BookAppointments
     */
    public M_BookAppointments(String username) {
        setTitle("Book Appointment - Manager");
        initComponents();
        setTable();
        displayAppointments();
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        appttable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NewApptButton = new javax.swing.JButton();
        DeleteApptButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Customer ID", "Description", "Appointment Date and Time"
            }
        ));
        jScrollPane1.setViewportView(appttable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("All Appointments");

        NewApptButton.setText("Add");
        NewApptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewApptButtonActionPerformed(evt);
            }
        });

        DeleteApptButton.setText("Delete");
        DeleteApptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteApptButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewApptButton)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteApptButton)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewApptButton)
                    .addComponent(DeleteApptButton)
                    .addComponent(backButton))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setTable(){
       table = (DefaultTableModel)appttable.getModel();
    };
   
     private void displayAppointments(){
        appttable.repaint();
         
         Service service = new Service(username);
         waitingAppointmentList = service.getPendingServiceList();
         table.setRowCount(0);
         
         
           for (String [] appointment : waitingAppointmentList){
               if (appointment[0] != null){
                 table.addRow(appointment);
             }
           }
        
    };
     
    private void DeleteApptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteApptButtonActionPerformed
        // TODO add your handling code here:
        try{
        int selectedRowIndex = appttable.getSelectedRow();
        Appointment appointment = new Appointment();
        String selection = waitingAppointmentList[selectedRowIndex][0];
        appointment.dltAppointment(selection);
        JOptionPane.showMessageDialog(this,"This appointment is deleted successfully");
        displayAppointments();
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Please select appointment", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeleteApptButtonActionPerformed

    private void NewApptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewApptButtonActionPerformed
        // TODO add your handling code here:
        M_CreateNewAppointment newappt = new M_CreateNewAppointment(username);
        newappt.setVisible(true);
        dispose();
    }//GEN-LAST:event_NewApptButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        M_home home = new M_home(username);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteApptButton;
    private javax.swing.JButton NewApptButton;
    private javax.swing.JTable appttable;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
