/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assg;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import com.github.lgooddatepicker.components.*;
import java.time.format.DateTimeFormatter;
import java.util.Date;

public class M_CreateNewAppointment extends javax.swing.JFrame {

    /**
     * Creates new form M_CreateNewAppointment
     */
    private String username;
    public M_CreateNewAppointment(String username) {
        initComponents();
        setTitle("Book a new appointment - Manager");
        this.username = username;
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                M_BookAppointments bookAppoint = new M_BookAppointments(username);
                bookAppoint.setVisible(true);
                dispose();
            }
        });
    }
    

    /**
     *
     * @param e
     */
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        c_idText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        dntText = new DateTimePicker();

        jLabel1.setText("Customer ID ");

        c_idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_idTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Description");

        jLabel3.setText("Date and Time");

        descriptionText.setColumns(20);
        descriptionText.setLineWrap(true);
        descriptionText.setRows(4);
        descriptionText.setTabSize(6);
        descriptionText.setToolTipText("");
        descriptionText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descriptionText);

        jLabel4.setText("New Appointment");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(c_idText)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addComponent(dntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(c_idText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(111, 111, 111)))
                .addComponent(saveButton)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_idTextActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
       saveButton.setEnabled(false);
       try{
        if (evt.getSource() == saveButton){
           int c_id = Integer.parseInt(c_idText.getText());
           String desc = descriptionText.getText().replace(",", "");
           String dnt = null;
           try {
               if (desc==null || desc.equals("")){
                   throw new Exception("Empty field found");
               }
               try{
                   DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMMM yyyy HH:mm:ss");
                   dnt = String.valueOf(dntText.getDateTimePermissive().format(formatter)).replace(",", "");
               }catch (Exception e){
                   throw new Exception("Invalid appointment datetime format");
               }
               // Check if date is future
               Date appointmentDateTime = new SimpleDateFormat("dd MMMM yyyy HH:mm:ss").parse(dnt);
               Date date = new Date();
               if (!appointmentDateTime.after(date)){
                    throw new Exception("Date and time must be future");
               }
               Appointment appt = new Appointment(c_id,desc,dnt);
               String appointID = appt.bookAppointment();
               if (appointID == null){
                   throw new Exception("Appointment booking failed");
               }
               System.out.println("New appointment has been saved successfully");
               JOptionPane.showMessageDialog(this,"New Appointment has been saved successfully");
           }
           catch(Exception e){
               System.out.println("Creating New Appointment Failed");
               JOptionPane.showMessageDialog(this,"Error Creating Appointment, "+e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
           }
        }
       }
       catch(NumberFormatException e){
           System.out.println("Please Enter the Details in the correct format");
           JOptionPane.showMessageDialog(this, "Please Enter the Details in the correct format", "Error", JOptionPane.ERROR_MESSAGE);
       }finally{
           M_BookAppointments bookAppoint = new M_BookAppointments(this.username);
           bookAppoint.setVisible(true);
           this.dispose();
       }
        
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_idText;
    private javax.swing.JTextArea descriptionText;
    private com.github.lgooddatepicker.components.DateTimePicker dntText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}