/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assg;

public class M_home extends javax.swing.JFrame {
    
    private String username;

    /**
     * Creates new form M_home
     */
    public M_home(String username) {
        this.username = username;
        setSize(600,400);
        setTitle("Home Page - Manager");
        initComponents();
        setLabel("Welcome, " + username);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                new LoginUI().setVisible(true);
                dispose();
            }
        });
    }
    
     private void setLabel(String WelcomeText){
        loginText.setText(WelcomeText);
     };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jSeparator1 = new javax.swing.JSeparator();
        manageUsersButton = new javax.swing.JButton();
        bookAppointmentsButton = new javax.swing.JButton();
        manageCustomersButtons = new javax.swing.JButton();
        loginText = new javax.swing.JLabel();

        manageUsersButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageUsersButton.setText("Manage Users");
        manageUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersButtonActionPerformed(evt);
            }
        });

        bookAppointmentsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookAppointmentsButton.setText("Book Appointments");
        bookAppointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAppointmentsButtonActionPerformed(evt);
            }
        });

        manageCustomersButtons.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageCustomersButtons.setText("Manage Customers");
        manageCustomersButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomersButtonsActionPerformed(evt);
            }
        });

        loginText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginText.setText("Welcome, ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bookAppointmentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(manageCustomersButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manageUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(loginText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookAppointmentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageCustomersButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookAppointmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAppointmentsButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == bookAppointmentsButton){
            navigateToBooking();
        }
    }//GEN-LAST:event_bookAppointmentsButtonActionPerformed

    private void manageUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == manageUsersButton){
            navigatetoManageUsers();
        }
    }//GEN-LAST:event_manageUsersButtonActionPerformed

    private void manageCustomersButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomersButtonsActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == manageCustomersButtons){
            navigatetoManageCustomer();
        }
    }//GEN-LAST:event_manageCustomersButtonsActionPerformed

    private void navigateToBooking(){
        M_BookAppointments bookappt = new M_BookAppointments(username);
        bookappt.setVisible(true);
        dispose();
    }
    
    private void navigatetoManageUsers(){
        M_ManageUsers manageusers = new M_ManageUsers(username);
        manageusers.setVisible(true);
        dispose();
    }
    
    private void navigatetoManageCustomer(){
        M_ManageCustomers managecustomers = new M_ManageCustomers(username);
        managecustomers.setVisible(true);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookAppointmentsButton;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loginText;
    private javax.swing.JButton manageCustomersButtons;
    private javax.swing.JButton manageUsersButton;
    // End of variables declaration//GEN-END:variables
}
