/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assg;

public class T_home extends javax.swing.JFrame {

    private String username;
    
    /**
     * Creates new form technician_home
     */
    public T_home(String username) {
        setSize(600,400);
        setTitle("Home Page - Technician");
        this.username = username;
        initComponents();
        setLabel("Welcome, " + username);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                new LoginUI().setVisible(true);
                dispose();
            }
        });
    }

    private void setLabel(String WelcomeText){
        loginText.setText(WelcomeText);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        viewAppointmentsButton = new javax.swing.JButton();
        paymentAndFeedbackButton = new javax.swing.JButton();
        loginText = new javax.swing.JLabel();

        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 10));
        jSeparator1.setRequestFocusEnabled(false);

        viewAppointmentsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewAppointmentsButton.setText("View Appointments");
        viewAppointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAppointmentsButtonActionPerformed(evt);
            }
        });

        paymentAndFeedbackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentAndFeedbackButton.setText("Payments and Feedbacks");
        paymentAndFeedbackButton.setToolTipText("");
        paymentAndFeedbackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        paymentAndFeedbackButton.setName("paymentandfeedbackbutton"); // NOI18N
        paymentAndFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentAndFeedbackButtonActionPerformed(evt);
            }
        });

        loginText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginText.setText("Welcome, ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(viewAppointmentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paymentAndFeedbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(loginText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentAndFeedbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAppointmentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewAppointmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAppointmentsButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == viewAppointmentsButton){
            navigateToTechiniciansAppointment();
        }
    }//GEN-LAST:event_viewAppointmentsButtonActionPerformed

    private void paymentAndFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentAndFeedbackButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == paymentAndFeedbackButton){
            navigateToPaymentAndFeedbacks();
            
        }
    }//GEN-LAST:event_paymentAndFeedbackButtonActionPerformed

    private void navigateToTechiniciansAppointment(){
        T_ViewAppointments viewappts = new T_ViewAppointments(username);
        viewappts.setVisible(true);
        dispose();
    }
    
    private void navigateToPaymentAndFeedbacks(){
        T_PaymentandFeedbacks pnf = new T_PaymentandFeedbacks(username);
        pnf.setVisible(true);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loginText;
    private javax.swing.JButton paymentAndFeedbackButton;
    private javax.swing.JButton viewAppointmentsButton;
    // End of variables declaration//GEN-END:variables

   
}
